services:
  nav:
    image: ghcr.io/datagutten/nav-gunicorn:${NAV_VERSION}
    volumes:
      - logs:/var/log/nav:Z
      - roomimages:/var/lib/nav/uploads/images/rooms:Z
    depends_on:
      - postgres
      - nav-backend
      - graphite-web
    env_file:
      - nav-variables.env
      - nav-common.env
    restart: always

  nav-backend:
    image: ghcr.io/datagutten/nav-backend:${NAV_VERSION}
    ports:
      - "162:162/udp"
    volumes:
    - logs:/var/log/nav:Z
    depends_on:
    - postgres
    - carbon-cache

    env_file:
    - nav-variables.env
    - nav-common.env
    restart: always

  ipdevpoll:
    image: ghcr.io/datagutten/nav-base:${NAV_VERSION}

    env_file:
    - nav-variables.env
    - nav-common.env
    depends_on:
    - postgres
    - carbon-cache
    restart: always
    command:
    - /usr/local/bin/ipdevpolld
    - -f # Run in foreground
    - -s # Log to stderr

  pping:
    image: ghcr.io/datagutten/nav-base:${NAV_VERSION}
    env_file:
    - nav-variables.env
    - nav-common.env
    depends_on:
    - postgres
    restart: always
    command:
    - /usr/local/bin/pping
    - -f # Run in foreground

  postgres:
    image: "docker.io/postgres:15"
    volumes:
      - postgres:/var/lib/postgresql/data:Z
    # The following vars are documented at https://hub.docker.com/_/postgres
    environment:
      - POSTGRES_PASSWORD=s3cret
      - POSTGRES_USER=nav
      - POSTGRES_DB=nav
    restart: always

  carbon-cache:
    image: ghcr.io/datagutten/nav-carbon-cache
    volumes:
      - whisper:/var/lib/graphite/whisper:z
    restart: always

  graphite-web:
    image: ghcr.io/datagutten/nav-graphite-web
    # We don't really want this to be public, since there is no authentication
    # ports:
    #   - "8000:80"
    environment:
      - TIME_ZONE=Europe/Oslo
      - CARBONLINK_HOSTS=carbon-cache:7002
    volumes:
      - whisper:/var/lib/graphite/whisper:z
    restart: always

  nginx:
    image: ghcr.io/datagutten/nav-nginx:${NAV_VERSION}
    ports:
    - "80:80"
    volumes:
      - roomimages:/home/app/nav_uploads

    depends_on:
    - nav
    restart: always

volumes:
  whisper:
    driver: local
  postgres:
    driver: local
  logs:
    driver: local
  roomimages:
    driver: local
