[program:alertengine]
command=/usr/local/bin/alertengine -f
user=nav
autorestart = true

[program:eventengine]
command=/usr/local/bin/eventengine -f
user=nav
autorestart = true

[program:servicemon]
command=/usr/local/bin/servicemon -f
user=nav
autorestart = true

[program:smsd]
command=/usr/local/bin/smsd -f
user=nav
autorestart = true

[program:snmptrapd]
command=/usr/sbin/snmptrapd -f
user=root
autorestart = true
