name: Create and publish a Docker image

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'

jobs:
  getversion:
    runs-on: ubuntu-latest
    name: Obtain NAV Version
    outputs:
      build-version: ${{ steps.set-version.outputs.nav_version }}
    steps:
    - name: Set NAV Build Version
      id: set-version
      run: |
        if [[ ${GITHUB_REF} == refs/heads/* || ${GITHUB_REF} == refs/pull/* ]]; then
          # Build from latest NAV commit
          NAV_VERSION=$(wget \
            -qO - https://api.github.com/repos/Uninett/nav/releases/latest \
            | awk '/tag_name/{print $4;exit}' FS='[""]')
        else
          # Build tag
          NAV_VERSION=${GITHUB_REF##*/}
        fi
        echo Building NAV ${NAV_VERSION}
        echo "nav_version=${NAV_VERSION}" >> $GITHUB_OUTPUT


  build:
    name: Build and push Docker Images
    runs-on: ubuntu-latest
    if: ${{ needs.getversion.outputs.build-version != '' }}
    needs: getversion
    env:
      NAV_VERSION: ${{ needs.getversion.outputs.build-version }}

    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: datagutten
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push NAV base image
      id: push_base
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        build-args: |
          NAV_VERSION=${{env.NAV_VERSION}}
        tags: |
          ghcr.io/datagutten/nav-base:${{ needs.getversion.outputs.build-version }} 
          ghcr.io/datagutten/nav-base:latest

    - name: Build and push NAV backend image
      id: push_backend
      uses: docker/build-push-action@v6
      with:
        context: nav-backend
        push: true
        build-args: |
          NAV_VERSION=${{env.NAV_VERSION}}
        tags: |
          ghcr.io/datagutten/nav-backend:${{ needs.getversion.outputs.build-version }} 
          ghcr.io/datagutten/nav-backend:latest

    - name: Build and push NAV carbon-cache image
      id: push_carbon_cache
      uses: docker/build-push-action@v6
      with:
        context: carbon-cache
        push: true
        build-args: |
          NAV_VERSION=${{env.NAV_VERSION}}
        tags: |
          ghcr.io/datagutten/nav-carbon-cache:${{ needs.getversion.outputs.build-version }} 
          ghcr.io/datagutten/nav-carbon-cache:latest

    - name: Build and push NAV Graphite web image
      id: push_graphite
      uses: docker/build-push-action@v6
      with:
        context: graphite-web
        push: true
        build-args: |
          NAV_VERSION=${{env.NAV_VERSION}}
        tags: |
          ghcr.io/datagutten/nav-graphite-web:${{ needs.getversion.outputs.build-version }} 
          ghcr.io/datagutten/nav-graphite-web:latest

    - name: Build and push NAV Gunicorn image
      id: push_gunicorn
      uses: docker/build-push-action@v6
      with:
        context: gunicorn
        push: true
        build-args: |
          NAV_VERSION=${{env.NAV_VERSION}}
        tags: |
          ghcr.io/datagutten/nav-gunicorn:${{ needs.getversion.outputs.build-version }} 
          ghcr.io/datagutten/nav-gunicorn:latest

    - name: Build and push NAV nginx image
      id: push_nginx
      uses: docker/build-push-action@v6
      with:
        context: nginx
        push: true
        build-args: |
          NAV_VERSION=${{env.NAV_VERSION}}
        tags: |
          ghcr.io/datagutten/nav-nginx:${{ needs.getversion.outputs.build-version }} 
          ghcr.io/datagutten/nav-nginx:latest
